name: arcestia.id
url: http://arcestia.id
copyright: 2016
permalink: pretty
assets:
  cache: true
exclude:
- script
- Gemfile
- Gemfile.lock
- scratch.md
- vendor
- test
- Rakefile
gems:
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
author:
  name: Laurensius Jeffrey Chandra
  email: arcestia@arcestia.id
  uri: http://arcestia.id
  twitter: arcestia
amazon_associate_id: arcestiaorg0d-20
branch: master
repository: arcestia/arcestia.github.io

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "arcestia"

# SEO
title: Laurensius Jeffrey Chandra
description: I keep learn, and stay foolish.

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
