name: Update Submodule and Build Jekyll Site

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true # Ensure submodules are checked out
        token: ${{ secrets.BOT_GITHUB_TOKEN }}

    - name: Configure git
      run: |
        git config --global user.email "160487326+Skiddle-Git@users.noreply.github.com"
        git config --global user.name "Skiddle Git Assistant"
        
    - name: Update Submodule
      run: |
        cd _posts/
        git fetch origin
        git merge origin/master --allow-unrelated-histories -m "Merge commit" || echo "Merge failed"
        cd ..
        git add _posts
        git commit -am "Post updated on $(date +'%Y-%m-%d %H:%M:%S')" || echo "No posts updates found"
    
    - name: Push changes
      run: git push origin HEAD:master
      # Adjust HEAD:master if your branch is different, e.g., HEAD:main

    - name: Build Jekyll site
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
