name: Update Submodule

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.BOT_GITHUB_TOKEN }}

    - name: Update Submodule
      run: |
        git submodule update --remote --merge

    - name: Configure git
      run: |
          git config user.email "160487326+Skiddle-Git@users.noreply.github.com"
          git config user.name "Skiddle Git Assistant"
  
    - name: Commit changes
      run: |
          git commit -am "Submodule updated" || echo "No changes to commit"
          git push
  
    - name: Build Jekyll site
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"